import os
import re

from docx import Document
from docx.shared import Pt
from fpdf import FPDF


# ---------------------------------------------------------
# TEXT CLEANING
# ---------------------------------------------------------

def sanitize_text(text: str) -> str:
    if not text:
        return ""

    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2026": "...",
        "\u00a0": " ",
        "\u2022": "-",
        "\u2192": "->",
        "\u00ae": "(R)",
        "\u2122": "(TM)",
        "⚖️": "",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    # Remove markdown symbols
    text = text.replace("**", "")
    text = text.replace("__", "")
    text = text.replace("***", "")

    # Remove very long underscore lines
    text = re.sub(r"_+", "Signature: ____________________", text)

    return text.strip()


# ---------------------------------------------------------
# TXT
# ---------------------------------------------------------

def format_txt(text: str) -> bytes:
    clean_text = sanitize_text(text)
    return clean_text.encode("utf-8")


# ---------------------------------------------------------
# DOCX
# ---------------------------------------------------------

def format_docx(
    text: str,
    doc_type: str = "Legal Document"
) -> bytes:

    text = sanitize_text(text)

    document = Document()

    title = document.add_paragraph()
    title.alignment = 1

    run = title.add_run(doc_type.upper())
    run.bold = True
    run.font.size = Pt(16)

    document.add_paragraph()

    for paragraph in text.split("\n"):

        paragraph = paragraph.strip()

        if not paragraph:
            continue

        if (
            paragraph.isupper()
            or paragraph.endswith(":")
            or re.match(r"^\d+[\.\)]\s+", paragraph)
        ):
            heading = document.add_paragraph()

            run = heading.add_run(paragraph)
            run.bold = True
            run.font.size = Pt(12)

        else:
            p = document.add_paragraph(paragraph)

            for run in p.runs:
                run.font.size = Pt(11)

    footer = document.sections[0].footer.paragraphs[0]

    footer.alignment = 1

    footer.text = (
        "Generated by LegalEase - AI Legal Document Generator"
    )

    temp_path = "temp_legal_document.docx"

    document.save(temp_path)

    with open(temp_path, "rb") as file:
        data = file.read()

    os.remove(temp_path)

    return data


# ---------------------------------------------------------
# PDF CLASS
# ---------------------------------------------------------

class LegalPDF(FPDF):

    def header(self):

        self.set_font("Helvetica", "B", 14)

        self.cell(
            0,
            10,
            "LegalEase",
            align="C"
        )

        self.ln(12)

    def footer(self):

        self.set_y(-15)

        self.set_font("Helvetica", "", 8)

        self.cell(
            0,
            10,
            "Generated by LegalEase - AI Legal Document Generator",
            align="C"
        )


# ---------------------------------------------------------
# SAFE LINE SPLITTER
# ---------------------------------------------------------

def split_long_text(text, max_length=75):

    words = text.split()

    lines = []

    current_line = ""

    for word in words:

        # If one word itself is extremely long
        if len(word) > max_length:

            if current_line:
                lines.append(current_line)
                current_line = ""

            for i in range(0, len(word), max_length):
                lines.append(
                    word[i:i + max_length]
                )

            continue

        if not current_line:

            current_line = word

        elif len(current_line) + 1 + len(word) <= max_length:

            current_line += " " + word

        else:

            lines.append(current_line)

            current_line = word

    if current_line:
        lines.append(current_line)

    return lines


# ---------------------------------------------------------
# PDF
# ---------------------------------------------------------

def format_pdf(
    text: str,
    doc_type: str = "Legal Document"
) -> bytes:

    text = sanitize_text(text)

    pdf = LegalPDF()

    pdf.set_auto_page_break(
        auto=True,
        margin=20
    )

    pdf.add_page()

    # Title
    pdf.set_font(
        "Helvetica",
        "B",
        16
    )

    pdf.cell(
        0,
        10,
        doc_type.upper(),
        align="C"
    )

    pdf.ln(12)

    # Body
    pdf.set_font(
        "Helvetica",
        "",
        10
    )

    paragraphs = text.split("\n")

    for paragraph in paragraphs:

        paragraph = paragraph.strip()

        if not paragraph:

            pdf.ln(4)

            continue

        # Heading detection
        is_heading = (
            paragraph.isupper()
            or paragraph.endswith(":")
            or re.match(
                r"^\d+[\.\)]\s+",
                paragraph
            )
        )

        if is_heading:

            pdf.set_font(
                "Helvetica",
                "B",
                11
            )

        else:

            pdf.set_font(
                "Helvetica",
                "",
                10
            )

        # SAFE SPLITTING
        safe_lines = split_long_text(
            paragraph,
            75
        )

        for line in safe_lines:

            pdf.cell(
                0,
                6,
                line,
                new_x="LMARGIN",
                new_y="NEXT"
            )

        pdf.ln(2)

    # Create temporary PDF
    temp_pdf = "temp_legal_document.pdf"

    pdf.output(temp_pdf)

    # Read PDF as bytes
    with open(
        temp_pdf,
        "rb"
    ) as file:

        pdf_data = file.read()

    # Delete temporary file
    try:
        os.remove(temp_pdf)
    except OSError:
        pass

    return pdf_data


# ---------------------------------------------------------
# HTML PREVIEW
# ---------------------------------------------------------

def format_html_preview(text: str) -> str:

    text = sanitize_text(text)

    html_parts = []

    for paragraph in text.split("\n"):

        paragraph = paragraph.strip()

        if not paragraph:
            continue

        escaped = (
            paragraph
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )

        if (
            paragraph.isupper()
            or paragraph.endswith(":")
        ):

            html_parts.append(
                f"<h3>{escaped}</h3>"
            )

        else:

            html_parts.append(
                f"<p>{escaped}</p>"
            )

    return "\n".join(html_parts)